### ISSUE TITLE
Unjustified errors in file and in problem list

### ISSUE THREAD

**Issue by erelsgl** [GrammaticalFramework/gf-eclipse-plugin#3]
I just started a new GF project, and copied the files from the "examples/hello" folder.

I see:

a. In the editor, in the "HelloEng.gf" file, many words are marked in red, with the same error message: 
"Couldn't resolve reference to Ident X"
Where X is: "Gender", "Masc", "Fem", "Recipient".
(This is probably related to the fact that these identifiers are defined in another file).

I tried to enter a space, save, clean the project, etc. - it didn't work, the errors are still there.
(There were no errors in building the grammar - only in the editor).

b. In the Project Explorer, all four files are marked with a red "X". This is probably due to c:

c. In the Problems panel, there is a problem for each file, with the same message: "Xtext check (normal)"

I use Eclipse Gallileo on Ubuntu 10.

**Comment by johnjcamilleri** [comment]
Hi Erel,
Consider the following:
1. Do you have automatic build turned on in Eclipse?
2. Are you running a new version of gf which has support for the `--tags` flag?
3. Could you look into your Eclipse log file and find any relevant messages?

**Comment by erelsgl** [comment]
1. Yes, I have automatic build.
2. I use version 3.3: 

$ gf --version
Grammatical Framework (GF) version 3.3
1. This is what I find in the log - I probably really don't have "--tags" flag support:

!ENTRY org.grammaticalframework.eclipse.ui 2 0 2012-02-27 16:31:54.970
!MESSAGE Build failed on: /gfdemo/ResEng.gf
unrecognized option `--tags'
You may want to try --help.

**Comment by johnjcamilleri** [comment]
Ok, there's your problem.
Unfortunately for the GF Eclipse Plugin to work, you need that `--tags` flag which currently means you have to build GF from source. This is of course quite inconvenient, but is only temporary until a new GF release is published.
I will ask around to see if this can be prioritized.

**Comment by johnjcamilleri** [comment]
Hi Erel
A new GF release is planned very soon, so if you wish to avoid building GF from source just hang on for a little longer and you will be able to directly use a new GF binary.

**Comment by erelsgl** [comment]
Thank you!

On Tue, Feb 28, 2012 at 1:46 PM, John J. Camilleri <
reply@reply.github.com

**Comment by johnjcamilleri** [comment]
As promised, the new [GF release 3.3.3](http://www.grammaticalframework.org/download/release-3.3.3.html) now includes the -tags feature which is needed by the GF Eclipse Plugin. This means one no longer needs to build GF from source in order to use the plugin. Enjoy!
