### ISSUE TITLE
Feature request: create a new context-free grammar

### ISSUE THREAD

**Issue by erelsgl** [GrammaticalFramework/gf-eclipse-plugin#4]
In File -> New -> GF Module, I think the options should also include: context-free grammar, EBNF grammar, etc. These are very useful.

**Comment by johnjcamilleri** [comment]
Noted, thanks!

**Comment by johnjcamilleri** [comment]
A wizard for creating context-free grammars has been as of 1.4.2.x. It allows you to create BNF (`*.cf`) and Extended BNF  BNF (`*.ebnf`) grammars as described [here](http://www.grammaticalframework.org/doc/gf-refman.html#toc55).
Note that the GF Eclipse Plugin has no syntax support for such grammars, and they will only be editable in Eclipse's plain text editor. Adding such support is not considered a goal of the GFEP.
