### ISSUE TITLE
Problem on Windows machines

### ISSUE THREAD

**Issue by johnjcamilleri** [GrammaticalFramework/gf-eclipse-plugin#6]
Wrong type of slash is used in scoping when opening tags files. This seems to be hardcoded as "/" but should be system-dependant.

**Comment by inariksit** [comment]
!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:06:25.323
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsI.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:24.899
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsI.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:26.927
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsI.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:28.097
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsPor.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:28.284
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\MutationsGle.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:28.487
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsGle.gf-tags

!ENTRY org.grammaticalframework.eclipse.ui 0 0 2012-03-07 18:07:28.627
!MESSAGE Couldn't find tags file platform:/resource/Foods/.gfbuild\FoodsEng.gf-tags
!SESSION 2012-03-09 11:39:30.124 -----------------------------------------------
eclipse.buildId=M20120208-0800
java.version=1.6.0_26
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fi_FI
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.core.resources 2 10035 2012-03-09 11:40:52.128
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.

**Comment by johnjcamilleri** [comment]
Note to self: Problem has been localised to somewhere in `org.grammaticalframework.eclipse.scoping.GFTagBasedGlobalScopeProvider.java` in generation of tag file URI's.
Also exception handling and reporting needs to be better here.

**Comment by johnjcamilleri** [comment]
This issue may now be solved as of version 1.4.1.201203131438.
Please test and check that you no longer receive this error message.
