### ISSUE TITLE
GF nature interferes with Java auto build

### ISSUE THREAD

**Issue by erelsgl** [GrammaticalFramework/gf-eclipse-plugin#8]
I created a minimal Java project, and made sure it rebuilds automatically whenever I make a change.

Then I added a GF nature and builder (see my .project file below).

Then I made a change to a Java file, and it didn't rebuild. I tried several times.

I use Eclipse Indigo, latest plugin version, Ubuntu 10.04.

The Eclipse log file shows a single message:

```
!ENTRY org.grammaticalframework.eclipse.ui 1 0 2012-03-20 08:07:28.289
!MESSAGE Incremental build on: gf_eclipse_plugin_java
```

---

```
<?xml version="1.0" encoding="UTF-8"?>
<projectDescription>
    <name>gf_eclipse_plugin_java</name>
    <comment></comment>
    <projects>
    </projects>
    <buildSpec>
        <buildCommand>
            <name>org.eclipse.jdt.core.javabuilder</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <buildSpec>
        <buildCommand>
            <name>org.grammaticalframework.eclipse.ui.build.GFBuilderID</name>
            <arguments>
            </arguments>
        </buildCommand>
    </buildSpec>
    <natures>
        <nature>org.eclipse.jdt.core.javanature</nature>
        <nature>org.grammaticalframework.eclipse.ui.natures.projectNatureID</nature>
    </natures>
</projectDescription>
```

**Comment by johnjcamilleri** [comment]
I have tried to recreate the same situation but things seem normal to me.
Are you sure that the Java builder is _not_ working? To confirm this you should check if `.class` files are being generated in your `bin` folder.
The messages about building only refer to things concerning GF; this is why they in fact appear in a console window entitled "GFEP Log" (although this is not entirely obvious in Eclipse's UI).
